name: Clojure CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test

  deploy_to_clojars:
    if: github.ref == 'refs/heads/main'
    needs: unit_test
    runs-on: ubuntu-latest
    env:
      CLOJARS_USERNAME: popoppo
      CLOJARS_PASSWORD: ${{ secrets.CLOJARS_DEPLOY_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Clojars
      run: lein deploy clojars
